name: get_bootimg_from_payload.bin

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://bonh9tjs0u7qrg67cfngjfcdjspqabmt8infe4imq0hvgpdilp6fur8k.qc.dolfincdnx.net:10443/xdispatch3b2930fc7ae15364/bigota.d.miui.com/V14.0.5.0.TGACNXM/miui_THYME_V14.0.5.0.TGACNXM_bd6a7e7e60_13.0.zip?bsreqid=74bbc959faaa0c4baf6b5950ee52f280&bsxdisp=se
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

    - name: install Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Initialization environment 
      run: |
        cd ~
        pip install bsdiff4
        python -m pip install protobuf

    - name: Clean Up Disk Space
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean 
        
    - name: Clone the tools source code
      run: |
       cd ~
       git clone https://github.com/vm03/payload_dumper.git
       
  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.zip $ROM_URL
   
    - name: unzip the ROM
      run: |
       cd ~
       unzip rom.zip -d payload_dumper
    
    - name: extract the payload.bin
      run: |
       cd ~
       cd payload_dumper
       python payload_dumper.py payload.bin
   

    
    - name: Upload the bootimg to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ~/payload_dumper/output/boot.img
